### ISSUE TITLE
Ordering of rows and columns for heatmaps

### ISSUE THREAD

**Issue by edomamaru** [Energy-Visualizer/eviz#18]
Possibly respect the aggregation levels that we already use.
- [ ] Without aggregation cluster them together
- [ ] Be able to see the aggregated and non aggregated 
- [ ] Boxes do not align

**Comment by edomamaru** [comment]
Do we want to keep this open even though we have industry and product aggregation?

**Comment by kenny5033** [comment]
Matrix ordering implemented with at least some level of aggregation available through industry and product aggregation. Closing accordingly.
