### ISSUE TITLE
Pretty up the query page

### ISSUE THREAD

**Issue by rpruim** [Energy-Visualizer/eviz#22]
Current view:

<img width="537" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/722231/8415e17a-ceb3-4788-8271-3785bb6e6871">

I like the center justified layout and the new controls.  So mainly confirming that #19 seems to have been a good improvement.

You comment in #19 that it is "not pretty", so this issue is a place holder for ideas about making it prettier.

* [x] "Get" should probably be more specific -- Perhaps "make plot"
* [x] Perhaps "Get" and "Download Data" should be in lower left and right corners?
* [x] Should country(ies) get the same center justified treatment?  (I think so, but I'd like to see how it looks.)  Also the singular plural is a bit weird because of English.
* [x] "including NEU" -> "include NEU"
* [x] a tough of space between "last stage" and the drop down?

**Comment by kenny5033** [comment]
requested enhancements made

**Comment by rpruim** [comment]
I'm not seeing all of these changes on the public-facing site.  Have they been deployed?

<img width="546" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/722231/8fb2f9eb-a6d4-4b31-860a-4ae55146608e">
