### ISSUE TITLE
Change Site Name

### ISSUE THREAD

**Issue by kenny5033** [Energy-Visualizer/eviz#24]
Current name is too close to https://visualizingenergy.org

**Comment by MatthewHeun** [comment]
How about "edb" (for energy database)? It is pretty easy to say. It is quick to type.

**Comment by MatthewHeun** [comment]
Also, I don't think this should be a backburner issue. We need to solve it soon, so we reduce the number of changes required later.

**Comment by kenny5033** [comment]
Just some quick ideas:
EcoSight, shorten to ECOS
EcoGraph, shorten to ECOG

They show that the project deals with the ecosystem and visualization, but lose the energy part....

**Comment by kenny5033** [comment]
Brainstorming session:
XDB for Exergy Database
PSUTDB or EPSUTDB or XPSUTDB
XVIZ or EXVIZ instead of EVIZ
XEDIS for exergy/energy display
XEVIEW for exergy/energy view
Celosia, greek for burned/aflame
Xenergeia, "energeia" is greek for energy
Xenergia
Xemergia
XEM, xergy-energy-materials
Blosxem (blos-zem)

**Comment by rpruim** [comment]
XEM is a Neo-pronoun, so perhaps not a good choice.

PSUTDB or EPSUTDB or XPSUTDB look like alphabet soup -- I'd downvote these.

I wouldn't tie the name too closely to minutia of current data and data-naming.  That doesn't grow well.

Of the items above, I sort of liking Xenergia.  It's pretty easy to detect "energy" in there, and given the list, it seems people like the letter X.  "eia" at the end seems like it will lead to lots of typos.

Viz is nice, but the site does more than visualize.  It is also a portal for downloading data.  For some users, that might be the more important feature.

**Comment by rpruim** [comment]
XenergiX?

**Comment by MatthewHeun** [comment]
I talked to Tania today. She wants to go with XEDIS. No name will be perfect 🙂.

**Comment by MatthewHeun** [comment]
XEDIS is a company name.

**Comment by MatthewHeun** [comment]
> XenergiX

There is a company in Mexico by that name. https://www.xenergix.com.mx.

**Comment by MatthewHeun** [comment]
energxia

Seems to have no presence on the web.

**Comment by kenny5033** [comment]
There is a company in Delhi with Xenergia https://www.zaubacorp.com/company/XENERGIA-POWER-SOLUTIONS-PRIVATE-LIMITED/U31900DL2022PTC394167#google_vignette
Among a good few others using Xenergia

**Comment by MatthewHeun** [comment]
I checked with Tania. She likes mexer, so we're going with mexer!

How should it be styled? Mexer? meXer? MeXeR?

**Comment by kenny5033** [comment]
Mexer (with that styling) has been chosen as the new project name!

**Comment by rpruim** [comment]
all lower case for the url?

**Comment by MatthewHeun** [comment]
> all lower case for the url?

I think domain names are case INsensitive. So https://mexer.site and https://MeXeR.SiTe both work.
