### ISSUE TITLE
Blue text of "Sign Up" too hard to read against dark background in Log in tile

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#26]
<img width="296" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/0d5d8ac6-21f1-4ec6-8113-3078d07f3c47">

To me "Sign Up" is barely visible.

**Comment by kenny5033** [comment]
Link colors changed to blues matching with the rest of the site.
