### ISSUE TITLE
Start page improvements

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#27]
<img width="629" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/80672950-0b95-4367-bf05-0f070722835a">

- [x] Suggest simplifying the  "What is EVIZ?" part to "EVIZ enables exploration of primary, final, and useful energy and exergy data." (I.e., remove the question.)
- [x] Eliminate the "How to use EVIZ?" section altogether.
- [x] Add references (Authors, title, journal, doi) as links to the following papers: https://doi.org/10.1088/2753-3751/ad4e39, https://doi.org/10.1016/j.apenergy.2024.123344, https://doi.org/10.1016/j.energy.2023.126775

**Comment by rpruim** [comment]
If you drop the bibtex references for the papers here, we may be able to generate the references directly from those.

**Comment by kenny5033** [comment]
Changes requested to papers section layout at last meeting have been made
