### ISSUE TITLE
Enhancements to data selection panel

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#28]
<img width="319" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/f292b19d-3107-4ab8-8312-216974afb7f0">

 - [x] GET and DOWNLOAD buttons collide when the page is too narrow
 - [x] Matrices --> PSUT matrices
 - [x] Rephrase "Select type of plot" to "Choose visualization" or simply "Visualization"
 - [x] Don't show "IEAEWEB2022" if the user lacks access to IEA data. Even better, find a way to reduce access to all future IEA data, too.
 - [x] "Get country(s)" --> "Country(ies)". Also, do we have the ability to choose multiple countries yet?
 - [x] Selected by method --> Method. However, the list of methods should be populated by types present in the data. At the moment, we have only "PCM".
 - [x] For energy type --> Energy type. Spell out E and X  (Energy, Exergy)
 - [x] To last stage --> Last stage. Radio buttons? We have only Final and Useful last stages at present (and probably far into the future)
 - [x] IEA, MW should also have "Both" as an option.
 - [x] Including NEU --> Include NEU
 - [x] Set reasonable defaults such that if the user just clicks "GET" a plot will be produced.
 - [x] Remember these selections for the next time the user logs in.

**Comment by edomamaru** [comment]
Enhancements have been made.
