### ISSUE TITLE
IEA access

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#29]
<img width="305" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/817787a4-62c7-43b3-b1cd-7803028ad403">

- [x] Suggest rephrasing this error message to "You do not have access to IEA data."
- [x] Add a contact email for questions
- [x] Add a link to the page where WEB data can be purchased: https://www.iea.org/data-and-statistics/data-product/world-energy-balances

**Comment by kenny5033** [comment]
all enhancements made
