### ISSUE TITLE
Admin Zone

### ISSUE THREAD

**Issue by kenny5033** [Energy-Visualizer/eviz#30]
A page or site that allows EVIZ administrators to view site usage and grant / remove IEA access.

**Comment by kenny5033** [comment]
Used Django's base admin page and added custom IEA access grant / revoke actions

**Comment by rpruim** [comment]
Which users have admin access?

**Comment by kenny5033** [comment]
@rpruim eviz_admin is a superuser created for this purpose and is the only one with access right now. When the changes with the admin page go live, we can upgrade our user accounts.
