### ISSUE TITLE
Too much data on an efficiency graph

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#31]
These parameters

<img width="523" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/37f0c246-d9f5-4819-9812-443e6a55a811">

lead to this graph:

<img width="1389" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/c3b2359c-e422-41ce-beac-6a4c11d89afa">

Each year has 2 data points, but it should have only 1. 

I'm not sure what is duplicated.

**Comment by rpruim** [comment]
Is that one point for IEA and one for MW for each year?  If so, we just need to set the grouping so that we get two overlaid line graphs, possibly in different colors.  They should also be labeled.

**Comment by kenny5033** [comment]
Edom and I looked at the table itself and found an unaccounted for variable called GrossNet, which has two values for every year. This will become a query option for xy efficiency plots.

**Comment by rpruim** [comment]
I wonder if it might be good to make some checks on the data to make sure it conforms to expectations.  Ideally, any time something does not this would be logged, or the team would receive an email or something.  Another option would be do go to some sort of alert/error page when funky things happen.  Perhaps a message could give a bit of an explanation of the problem and the user could be prompted to contact us if they think what they tried should actually work.

This would help catch edge cases like this during development (and possibly also once we have real users, who are likely to try combinations that have not been tested).

**Comment by kenny5033** [comment]
@rpruim I moved your comment into a new issue to track it specifically.
