### ISSUE TITLE
Implement info blurbs for main query categories

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#39]
| Category | blurb |
| --------- | ----- |
| Dataset | Choose the dataset of interest |
| Country(ies) | Choose the countries of interest. Click "Add Country" to enable additional countries. |
| Method | Choose the method of accounting for the primary equivalent of renewable electricity. |
| Energy type | Choose one of energy or exergy. Energy is a heat quantification of energy. Exergy is a work quantification of energy. |
| Last stage | Choose the last stage of the energy conversion chain, either final or useful. |
| With IEAMW | Choose IEA data only, muscle work data only (MW) or both. |
| Include NEU | Choose whether to include non-energy uses (NEU) of energy carriers in final demand. |

**Comment by edomamaru** [comment]
Info blurbs have been added!
