### ISSUE TITLE
Compare Ghana 1971 sankeys

### ISSUE THREAD

**Issue by edomamaru** [Energy-Visualizer/eviz#40]
![Screenshot 2024-07-09 114640](https://github.com/Energy-Visualizer/eviz/assets/88850851/67126d21-e42f-41a3-b01a-0ed049ef8b31)

![Screenshot 2024-07-09 114451](https://github.com/Energy-Visualizer/eviz/assets/88850851/3e510b7d-7cea-46c3-9dae-3cbdff835eae)

Here is the data for Ghana 1971

[eviz_data (1).csv](https://github.com/user-attachments/files/16145792/eviz_data.1.csv)

**Comment by kenny5033** [comment]
Closing issue for now.
