### ISSUE TITLE
Make text of radio buttons part of the effective clickable area for a radio button

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#42]
In this window:

<img width="150" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/e65aaa60-be30-4d80-b472-ccb20296c7c4">

clicking anywhere in the words "X-Y Plot" should select the X-Y Plot button.

**Comment by kenny5033** [comment]
All applicable fields have this functionality now.
