### ISSUE TITLE
When downloading data, E and X should be checkboxes, not radio buttons (and maybe for other things)

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#43]
When downloading matrix data, users may want to download BOTH energy and exergy data. So this bit of the UI:

<img width="254" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/5effcf93-e587-4393-b2bd-7f7ef25711b6">

should be checkboxes when choosing "PSUT matrices" in the Visualization section.

**Comment by kenny5033** [comment]
@MatthewHeun
Those changes should be live. Please try reloading your browser cache and see if they are then displaying correctly.

Cmd+Shift+R on Mac will do this I believe.
