### ISSUE TITLE
Buttons should dynamically appear based on visualization choice.

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#44]
<img width="430" alt="image" src="https://github.com/Energy-Visualizer/eviz/assets/3308246/757fa153-912f-4878-aff0-985b1709e41f">

Only the "Download Data" should appear if the user has selected "PSUT matrices" for their visualization.

**Comment by kenny5033** [comment]
Download data button now only appears in the matrix menu.
