### ISSUE TITLE
Add a paper to the splash page

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#68]
Paul Steenwyk, Matthew Kuperus Heun, Paul E. Brockway, Tania Sousa, and Sofia Henriques. The contributions of muscle and machine work to land and labor productivity in world agriculture since 1800. Biophysical Economics and Sustainability, 7(2):1–17, 2022. Doi: 10.1007/s41247-022-00096-z

**Comment by edomamaru** [comment]
Paper has been added.
