### ISSUE TITLE
Change labels in matrix view

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#69]
In this view:

<img width="221" alt="image" src="https://github.com/user-attachments/assets/026e1a91-8070-4b94-b82d-00554ad579f8">

x and y don't have much meaning from an energy point of view. (They do have meaning from the plotting point of view. 

All matrix relationships are "from" (in rows) "to" (in columns). So it would be nice to do the following:

* Swap the order of x and y in the popup window.
* Change names: y --> "From", x --> "To"

Is that possible?

**Comment by edomamaru** [comment]
Changed the Y and X labels to 'From' and 'To' respectively.
