### ISSUE TITLE
Wording for acknowledgements

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#74]
In the acknowledgements section, we should include the following text:

Development of the Mexer website in Summer 2024 was made possible by a generous grant from the Energy Economics journal to Instituto Superior Téchnico, Lisbon, Portugal with a subcontract to Calvin University.

**Comment by rpruim** [comment]
This is something I can easily do, so I'd let the students prioritize other things before taking off for a while.

**Comment by edomamaru** [comment]
This has been done.
