### ISSUE TITLE
Fix appearance of Sankey diagrams

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/eviz#75]
A possible way to "fix" the appearance of the Sankey diagrams is to add a column to the Index table named "SankeyColumn". This column would contain integers that indicate which column of a Sankey diagram should contain the particular industry or energy carrier. I think we can make a pretty good guess which column should contain which Industry and which Product. For example, all "Resources [of XXXX]" industries would be in column 1. All columns of the Y matrix would be in the rightmost column. Last stage final will have fewer columns than last stage useful.

If we go this route, there will be more than 5 columns in the Sankey diagram, but I think that's OK.

**Comment by rpruim** [comment]
Closing in favorof #67
